spring:
  application:
    name: atlas

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/atlas}
    username: ${SPRING_DATASOURCE_USERNAME:atlas}
    password: ${SPRING_DATASOURCE_PASSWORD:atlas}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${PORT:8080}